# app/Dockerfile

FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip3 install -r requirements.txt

ENV HOST=0.0.0.0

HEALTHCHECK CMD curl --fail http://localhost:8080/

ENTRYPOINT ["python", "slack_bot.py"]
